{% set name = "unfold" %}
{% set version = "1.2.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3126c538475c00c34bdcc74ffa0b7b4b26d60164f0931cc99014b5761dc92766

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bw2calc
    - bw2data
    - bw2io
    - datapackage
    - numpy <2.0.0
    - pandas
    - prettytable
    - pyprind
    - python >={{ python_min }}
    - pyyaml
    - scipy
    - sparse
    - wurst >=0.4.0

test:
  imports:
    - unfold
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/polca/unfold
  summary: 'Unpacks LCA scenario databases.'
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  dev_url: https://github.com/polca/unfold

extra:
  recipe-maintainers:
    - m-rossi
