{% set name = "unfold" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8a68f36bd58e036f920435d41fa8edc85a3643ec26b4507b3ca8eee6b491560

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
  run:
    - bw2data
    - bw2io
    - datapackage
    - numpy
    - pandas
    - prettytable
    - pyprind
    - python >=3.10
    - pyyaml
    - scipy
    - sparse
    - wurst >=0.4.0

test:
  imports:
    - unfold

about:
  home: https://github.com/polca/unfold
  summary: 'Unpacks LCA scenario databases.'
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  dev_url: https://github.com/polca/unfold

extra:
  recipe-maintainers:
    - m-rossi
