{% set name = "unfold" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 678e62203c2bbaf470d1bfdac814671a8090f23cb54cef5dc33d4b4161481b39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
  run:
    - bw2calc
    - bw2data
    - bw2io
    - datapackage
    - numpy <2.0.0
    - pandas
    - prettytable
    - pyprind
    - python >=3.10
    - pyyaml
    - scipy
    - sparse
    - wurst >=0.4.0

test:
  imports:
    - unfold

about:
  home: https://github.com/polca/unfold
  summary: 'Unpacks LCA scenario databases.'
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  dev_url: https://github.com/polca/unfold

extra:
  recipe-maintainers:
    - m-rossi
